### PR TITLE
Fix varchar type cast

### PR DESCRIPTION
**Pull request by dingn1**

### CODE REVIEW

**Review by TSMMark — APPROVED** [review]
Lgtm if it works.. Are there unit tests for this lib or no?

**Comment by dingn1** [comment]
There are unit tests but it does not get run on our fork I think.

**Comment by dingn1** [comment]
Tested on staging for artists table it worked

**Review by MVV90 — APPROVED** [review]

**Comment by dingn1** [comment]
Screen Shot 2019-04-24 at 4 38 04 PM
Screen Shot 2019-04-24 at 4 38 28 PM

**Comment by dingn1** [comment]
Closing as this pr does nothing

**Pull request closed without merging**
